<a href="https://colab.research.google.com/github/JinLeeGG/AI_Project_Preparation/blob/main/3.%20Data%20Analysis/02.%20Pandas/2_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

https://ryuzyproject.tistory.com/36

# 1. 판다스(Pandas)
판다스(Pandas)는 데이터 분석을 위한 파이썬 라이브러리 중 하나로, 표 형태의 데이터나 다양한 형태의 데이터를 쉽게 처리하고 분석할 수 있도록 도와주는 도구입니다. 주로 데이터프레임(DataFrame)이라는 자료구조를 제공하며, 이를 통해 테이블 형태의 데이터를 다루기 용이합니다.

In [1]:
!pip install pandas

Requirement already satisfied: pandas in /usr/local/lib/python3.11/dist-packages (2.2.2)
Requirement already satisfied: numpy>=1.23.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.11/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.11/dist-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.11/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [2]:
import pandas as pd

# 2. Series와 DataFrame

### 1. Series

Series는 1차원 배열과 같은 자료구조로 하나의 열을 나타냅니다. 또한 각 요소는 인덱스(index)와 값(value)으로 구성되어 있습니다. 값은 넘파이의 ndarray 기반으로 저장됩니다. Series는 다양한 데이터 타입을 가질 수 있으며 정수, 실수, 문자열 등 다양한 형태의 데이터를 담을 수 있습니다.

In [6]:
idx = ['김사과', '반하나', '오렌지', '이메론', '배애리']
data = [67, 75, 90, 62, 98]

# pd.Series(데이터, 인덱스, ...)
pd.Series(data)

0    67
1    75
2    90
3    62
4    98
dtype: int64

In [8]:
se1 = pd.Series(data, idx)
se1

김사과    67
반하나    75
오렌지    90
이메론    62
배애리    98
dtype: int64

In [11]:
# se1의 index 값을 출력
print(se1.index)
# se1의 value 값을 출력 (ndarray로 저장됨)
print(se1.values)
print(type(se1.values)) # value는 ndarray 이다.

Index(['김사과', '반하나', '오렌지', '이메론', '배애리'], dtype='object')
[67 75 90 62 98]
<class 'numpy.ndarray'>

### 2. DataFrame

데이터프레임(DataFrame)은 판다스(Pandas) 라이브러리에서 제공하는 중요하고 강력한 데이터 구조로, 2차원의 테이블 형태 데이터를 다루는 데 사용됩니다. 또한 각 요소는 인덱스(index), 열(column), 값(value)으로 구성되어 있습니다. 데이터프레임은 행과 열로 이루어져 있으며, 각 열은 다양한 데이터 타입을 가질 수 있습니다. 값은 넘파이의 ndarray 기반으로 저장됩니다.

In [12]:
data = [[67, 93, 91],
        [75, 68, 96],
        [87, 81, 82],
        [62, 70, 75],
        [98, 56, 87]]

indx = idx = ['김사과', '반하나', '오렌지', '이메론', '배애리']
col = ['국어', '영어', '수학']

In [13]:
# pd.DataFrame(데이터, 인덱스, 컬럼, ...)
pd.DataFrame(data)

    0   1   2
0  67  93  91
1  75  68  96
2  87  81  82
3  62  70  75
4  98  56  87

In [14]:
pd.DataFrame(data, idx)

      0   1   2
김사과  67  93  91
반하나  75  68  96
오렌지  87  81  82
이메론  62  70  75
배애리  98  56  87

In [16]:
pd.DataFrame(data, idx, col)

     국어  영어  수학
김사과  67  93  91
반하나  75  68  96
오렌지  87  81  82
이메론  62  70  75
배애리  98  56  87

In [19]:
# 매개변수의 이름을 적어주면 순서의 관계가 없다.
df = pd.DataFrame(index=idx, columns=col, data=data)
df

     국어  영어  수학
김사과  67  93  91
반하나  75  68  96
오렌지  87  81  82
이메론  62  70  75
배애리  98  56  87

In [21]:
print(df.index) # object type (문자가 들어가는건 모두 object. String이 존재하지 않음)
print(df.columns)
print(df.values) # ndarray

Index(['김사과', '반하나', '오렌지', '이메론', '배애리'], dtype='object')
Index(['국어', '영어', '수학'], dtype='object')
[[67 93 91]
 [75 68 96]
 [87 81 82]
 [62 70 75]
 [98 56 87]]

In [24]:
# 딕셔너리를 사용하여 데이터프레임을 생성하기
dic = {
    '국어':[67, 75, 76, 62, 98],
    '영어':[93, 68, 81, 70, 56],
    '수학':[91, 96, 82, 75, 87]
}

df = pd.DataFrame(data=dic, index=idx)
df

     국어  영어  수학
김사과  67  93  91
반하나  75  68  96
오렌지  76  81  82
이메론  62  70  75
배애리  98  56  87

# 3. CSV 파일 읽어오기
CSV 파일은 Comma-Separated Values(쉼표로 구분된 값) 파일의 약자로, 데이터를 단순한 텍스트 형식으로 저장하는 데 사용되는 파일 형식입니다.

In [27]:
df = pd.read_csv("/content/drive/MyDrive/Python_Computer Vision With AI/3. Data Analysis/data/idol.csv")
df

      이름     그룹   소속사  성별        생년월일      키  혈액형  브랜드평판지수
0     지민  방탄소년단   빅히트  남자  1995-10-13  174.0    A  6267302
1     정국  방탄소년단   빅히트  남자  1997-09-01  179.0    A  5805844
2     민지    뉴진스   어도어  여자  2004-05-07  169.0    A  4437081
3     하니    뉴진스   어도어  여자  2004-10-06  161.7    O  4161153
4      뷔  방탄소년단   빅히트  남자  1995-12-30  179.0   AB  3470048
5    다니엘    뉴진스   어도어  여자  2005-04-11  165.0  NaN  2341271
6     혜인    뉴진스   어도어  여자  2008-04-21  170.0    O  2301785
7     지수   블랙핑크   와이지  여자  1995-01-03  162.0    A  2227460
8     해린    뉴진스   어도어  여자  2006-05-15  164.5    B  2173376
9     태연   소녀시대   에스엠  여자  1989-03-09    NaN    A  2079866
10    RM  방탄소년단   빅히트  남자  1994-09-12  181.0    A  2069499
11    제니   블랙핑크   와이지  여자  1996-01-16  163.0    B  2069250
12   옹성우    워너원  판타지오  남자  1995-08-25  179.0    A  1954327
13    리사   블랙핑크   와이지  여자  1997-03-27  167.0    A  1912800
14    로제   블랙핑크   와이지  여자  1997-02-11  168.0    B  1888132
15    윤아   소녀시대   에스엠  여자  1990-05-30  168.0    B  1885297
16    조이   레드벨벳   빅히트  여자  1996-09-03  168.0    A  1830514
17    슬기   레드벨벳   빅히트  여자  1994-02-10  161.0    A  1741767
18  강다니엘    워너원   NaN  남자  1996-12-10  182.0    A  1706444
19     진  방탄소년단   빅히트  남자  1992-12-04  179.0    O  1680587

In [28]:
type(df)

pandas.core.frame.DataFrame

# 4. 데이터프레임 기본 정보 알아보기

In [29]:
# 20 entries
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   이름       20 non-null     object
 1   그룹       20 non-null     object
 2   소속사      19 non-null     object
 3   성별       20 non-null     object
 4   생년월일     20 non-null     object
 5   키        19 non-null     float64
 6   혈액형      19 non-null     object
 7   브랜드평판지수  20 non-null     int64
dtypes: float64(1), int64(1), object(6)
memory usage: 1.4+ KB

In [30]:
# column 출력 (행)
df.columns

Index(['이름', '그룹', '소속사', '성별', '생년월일', '키', '혈액형', '브랜드평판지수'], dtype='object')

In [31]:
# 기존 column 교체
new_columns = ['name', 'group', 'company', 'gender', 'birthday', 'height', 'blood', 'brand']
df.columns = new_columns
df

    name  group company gender    birthday  height blood    brand
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587

In [32]:
# describe(): 통계 정보를 반환
# 50%는 데이터셋중에 딱 중간값 (실제존재하는 값)
# 25% , 75% 도 동일
# 숫자 정보만 나타낸다.
df.describe()

           height         brand
count   19.000000  2.000000e+01
mean   170.536842  2.700190e+06
std      7.225204  1.381919e+06
min    161.000000  1.680587e+06
25%    164.750000  1.887423e+06
50%    168.000000  2.074682e+06
75%    179.000000  2.623465e+06
max    182.000000  6.267302e+06

In [34]:
# 숫자정보 외에, 문자정보도 추가시킬수 있다.
df.describe(include=object) # Unique:중복없는값 Top: 최빈값, freq: 최빈값의 빈도

       name  group company gender    birthday blood
count    20     20      19     20          20    19
unique   20      6       5      2          20     4
top      지민  방탄소년단     빅히트     여자  1995-10-13     A
freq      1      5       7     13           1    11

In [35]:
# 원하는 개수의 데이터 보기
df.head() # 상위 5개의 row를 출력

  name  group company gender    birthday  height blood    brand
0   지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1   정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2   민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
3   하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
4    뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048

In [36]:
df.tail() # 하위 5개의 row를 출력

    name  group company gender    birthday  height blood    brand
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587

In [37]:
df.tail(2) # 하위 2개의 row를 출력

    name  group company gender    birthday  height blood    brand
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587

In [38]:
# 정렬하기
df.sort_index() # index로 오름차순 정렬: 기본값

    name  group company gender    birthday  height blood    brand
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587

In [39]:
df.sort_index(ascending=False) # index로 내림차순 정렬

    name  group company gender    birthday  height blood    brand
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302

In [41]:
# 특정 값을이용해서 정렬
df.sort_values(by='height', ascending=False) # 키로 내림차순 정렬

    name  group company gender    birthday  height blood    brand
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866

In [42]:
# NAN은 맨 밑으로 고정된다.
df.sort_values(by='height') # 키로 오름차순 정렬

    name  group company gender    birthday  height blood    brand
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866

In [43]:
 # 키로 내림차순 정렬. NaN을 위로 올림
df.sort_values(by='height', ascending=False, na_position='first')

    name  group company gender    birthday  height blood    brand
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767

In [46]:
# 1차 정렬: 키(내림차순),
# 2차 정렬 (같은 키일떄): 브랜드(내림차순)
df.sort_values(by=['height', 'brand'], ascending=[False, False], na_position='last')

    name  group company gender    birthday  height blood    brand
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
9     태연   소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866

# 5. 데이터 다루기

In [47]:
df.head()

  name  group company gender    birthday  height blood    brand
0   지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1   정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2   민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
3   하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
4    뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048

In [49]:
df['blood'] # df.blood (동일)

0       A
1       A
2       A
3       O
4      AB
5     NaN
6       O
7       A
8       B
9       A
10      A
11      B
12      A
13      A
14      B
15      B
16      A
17      A
18      A
19      O
Name: blood, dtype: object

In [51]:
type(df['blood'])

pandas.core.series.Series

In [52]:
df.head(3)

  name  group company gender    birthday  height blood    brand
0   지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1   정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2   민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081

In [53]:
df[:3]

  name  group company gender    birthday  height blood    brand
0   지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1   정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2   민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081

In [54]:
# loc 인덱싱: 컬럼 인덱싱
df.loc[:, 'name'] # 전체행, 열은 이름만
# df['name'] or df.name

0       지민
1       정국
2       민지
3       하니
4        뷔
5      다니엘
6       혜인
7       지수
8       해린
9       태연
10      RM
11      제니
12     옹성우
13      리사
14      로제
15      윤아
16      조이
17      슬기
18    강다니엘
19       진
Name: name, dtype: object

In [55]:
# 2~5까지 가져오기 (끝 번호를 포함한 index 번호이다.)
df.loc[2:5, 'name'] # 5번을 포함

2     민지
3     하니
4      뷔
5    다니엘
Name: name, dtype: object

In [56]:
# 여러 columns 를 가져올수 있다. (슬라이싱)
df.loc[2:5, ['name', 'gender', 'height']]

  name gender  height
2   민지     여자   169.0
3   하니     여자   161.7
4    뷔     남자   179.0
5  다니엘     여자   165.0

In [57]:
df.loc[[2,5], ['name', 'gender', 'height']]

  name gender  height
2   민지     여자   169.0
5  다니엘     여자   165.0

In [59]:
df.loc[[2,5], 'name':'height']

  name group company gender    birthday  height
2   민지   뉴진스     어도어     여자  2004-05-07   169.0
5  다니엘   뉴진스     어도어     여자  2005-04-11   165.0

In [60]:
# iloc 인덱싱: index로 인덱싱
df.iloc[:, 0] # 다 포함하되 0번 콜롬만 가져오기

0       지민
1       정국
2       민지
3       하니
4        뷔
5      다니엘
6       혜인
7       지수
8       해린
9       태연
10      RM
11      제니
12     옹성우
13      리사
14      로제
15      윤아
16      조이
17      슬기
18    강다니엘
19       진
Name: name, dtype: object

In [62]:
df.iloc[:, 0:3] # 3을 포함하지 않음 (이건 범위를 포함하지 않는다)

    name  group company
0     지민  방탄소년단     빅히트
1     정국  방탄소년단     빅히트
2     민지    뉴진스     어도어
3     하니    뉴진스     어도어
4      뷔  방탄소년단     빅히트
5    다니엘    뉴진스     어도어
6     혜인    뉴진스     어도어
7     지수   블랙핑크     와이지
8     해린    뉴진스     어도어
9     태연   소녀시대     에스엠
10    RM  방탄소년단     빅히트
11    제니   블랙핑크     와이지
12   옹성우    워너원    판타지오
13    리사   블랙핑크     와이지
14    로제   블랙핑크     와이지
15    윤아   소녀시대     에스엠
16    조이   레드벨벳     빅히트
17    슬기   레드벨벳     빅히트
18  강다니엘    워너원     NaN
19     진  방탄소년단     빅히트

In [63]:
df.iloc[:, [0, 3]] # 0, 3콜롬

    name gender
0     지민     남자
1     정국     남자
2     민지     여자
3     하니     여자
4      뷔     남자
5    다니엘     여자
6     혜인     여자
7     지수     여자
8     해린     여자
9     태연     여자
10    RM     남자
11    제니     여자
12   옹성우     남자
13    리사     여자
14    로제     여자
15    윤아     여자
16    조이     여자
17    슬기     여자
18  강다니엘     남자
19     진     남자

In [64]:
df.iloc[1:5, 0:2] # 1~5가 되기 직전까지, 0부터 2가되기 직전까지

  name  group
1   정국  방탄소년단
2   민지    뉴진스
3   하니    뉴진스
4    뷔  방탄소년단

In [65]:
# 모든 데이터를 True False로 나눈다.
df['height'] >= 180 # 키가 180이 넘는사람들

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18     True
19    False
Name: height, dtype: bool

In [66]:
df[df['height'] >= 180] # 키가 180이 넘는 사람의 데이터 출력

    name  group company gender    birthday  height blood    brand
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444

In [69]:
# 키가 180이 넘는 사람의 이름만 보고싶다면
df[df['height'] >= 180]['name'] # df['name'][df['height'] >= 180] (같은 아웃풋)

10      RM
18    강다니엘
Name: name, dtype: object

In [70]:
# 180이 넘는 사람의 이름, 성별, 키를 불러와
df[df['height'] >= 180][['name', 'gender', 'height']]

    name gender  height
10    RM     남자   181.0
18  강다니엘     남자   182.0

In [71]:
# loc 이용해서 데이터 전처리
df.loc[df['height'] >= 180, ['name', 'gender', 'height']]

    name gender  height
10    RM     남자   181.0
18  강다니엘     남자   182.0

In [72]:
company = ['빅히트', '어도어']
df['company'].isin(company)

0      True
1      True
2      True
3      True
4      True
5      True
6      True
7     False
8      True
9     False
10     True
11    False
12    False
13    False
14    False
15    False
16     True
17     True
18    False
19     True
Name: company, dtype: bool

In [73]:
df[df['company'].isin(company)] # df.loc[df['company'].isin(company),:]

   name  group company gender    birthday  height blood    brand
0    지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1    정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2    민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
3    하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
4     뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
5   다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
6    혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
8    해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
10   RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
16   조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
17   슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
19    진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587

# 6. 결측값
결측값은 값이 누락된 데이터를 의미하며, 판다스에서는 일반적으로 NaN으로 표시됩니다.

In [74]:
df.info()
# 19라고 되어있으면 1개씩 빠진거다.

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20 entries, 0 to 19
Data columns (total 8 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   name      20 non-null     object
 1   group     20 non-null     object
 2   company   19 non-null     object
 3   gender    20 non-null     object
 4   birthday  20 non-null     object
 5   height    19 non-null     float64
 6   blood     19 non-null     object
 7   brand     20 non-null     int64
dtypes: float64(1), int64(1), object(6)
memory usage: 1.4+ KB

In [75]:
df.isna() # 전체데이터에서 nan만 true로 나온다.

     name  group  company  gender  birthday  height  blood  brand
0   False  False    False   False     False   False  False  False
1   False  False    False   False     False   False  False  False
2   False  False    False   False     False   False  False  False
3   False  False    False   False     False   False  False  False
4   False  False    False   False     False   False  False  False
5   False  False    False   False     False   False   True  False
6   False  False    False   False     False   False  False  False
7   False  False    False   False     False   False  False  False
8   False  False    False   False     False   False  False  False
9   False  False    False   False     False    True  False  False
10  False  False    False   False     False   False  False  False
11  False  False    False   False     False   False  False  False
12  False  False    False   False     False   False  False  False
13  False  False    False   False     False   False  False  False
14  False  False    False   False     False   False  False  False
15  False  False    False   False     False   False  False  False
16  False  False    False   False     False   False  False  False
17  False  False    False   False     False   False  False  False
18  False  False     True   False     False   False  False  False
19  False  False    False   False     False   False  False  False

In [76]:
df.isnull() # NaN을 True

     name  group  company  gender  birthday  height  blood  brand
0   False  False    False   False     False   False  False  False
1   False  False    False   False     False   False  False  False
2   False  False    False   False     False   False  False  False
3   False  False    False   False     False   False  False  False
4   False  False    False   False     False   False  False  False
5   False  False    False   False     False   False   True  False
6   False  False    False   False     False   False  False  False
7   False  False    False   False     False   False  False  False
8   False  False    False   False     False   False  False  False
9   False  False    False   False     False    True  False  False
10  False  False    False   False     False   False  False  False
11  False  False    False   False     False   False  False  False
12  False  False    False   False     False   False  False  False
13  False  False    False   False     False   False  False  False
14  False  False    False   False     False   False  False  False
15  False  False    False   False     False   False  False  False
16  False  False    False   False     False   False  False  False
17  False  False    False   False     False   False  False  False
18  False  False     True   False     False   False  False  False
19  False  False    False   False     False   False  False  False

In [77]:
df.notnull() # NaN이 False

    name  group  company  gender  birthday  height  blood  brand
0   True   True     True    True      True    True   True   True
1   True   True     True    True      True    True   True   True
2   True   True     True    True      True    True   True   True
3   True   True     True    True      True    True   True   True
4   True   True     True    True      True    True   True   True
5   True   True     True    True      True    True  False   True
6   True   True     True    True      True    True   True   True
7   True   True     True    True      True    True   True   True
8   True   True     True    True      True    True   True   True
9   True   True     True    True      True   False   True   True
10  True   True     True    True      True    True   True   True
11  True   True     True    True      True    True   True   True
12  True   True     True    True      True    True   True   True
13  True   True     True    True      True    True   True   True
14  True   True     True    True      True    True   True   True
15  True   True     True    True      True    True   True   True
16  True   True     True    True      True    True   True   True
17  True   True     True    True      True    True   True   True
18  True   True    False    True      True    True   True   True
19  True   True     True    True      True    True   True   True

In [78]:
df['height'].isna() #height만 nan

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9      True
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
Name: height, dtype: bool

In [79]:
df[df['height'].isna()] # height가 nan인것만 뽑기

  name group company gender    birthday  height blood    brand
9   태연  소녀시대     에스엠     여자  1989-03-09     NaN     A  2079866

In [81]:
df[df['height'].isna()]['name'] # height가 nan인것중 이름만 뽑기

9    태연
Name: name, dtype: object

In [82]:
df[df['height'].notnull()] # height값이 nan이 아닌사람만 뽑기
# df[~df['height'].isnull()]  # 같은결과

    name  group company gender    birthday  height blood    brand
0     지민  방탄소년단     빅히트     남자  1995-10-13   174.0     A  6267302
1     정국  방탄소년단     빅히트     남자  1997-09-01   179.0     A  5805844
2     민지    뉴진스     어도어     여자  2004-05-07   169.0     A  4437081
3     하니    뉴진스     어도어     여자  2004-10-06   161.7     O  4161153
4      뷔  방탄소년단     빅히트     남자  1995-12-30   179.0    AB  3470048
5    다니엘    뉴진스     어도어     여자  2005-04-11   165.0   NaN  2341271
6     혜인    뉴진스     어도어     여자  2008-04-21   170.0     O  2301785
7     지수   블랙핑크     와이지     여자  1995-01-03   162.0     A  2227460
8     해린    뉴진스     어도어     여자  2006-05-15   164.5     B  2173376
10    RM  방탄소년단     빅히트     남자  1994-09-12   181.0     A  2069499
11    제니   블랙핑크     와이지     여자  1996-01-16   163.0     B  2069250
12   옹성우    워너원    판타지오     남자  1995-08-25   179.0     A  1954327
13    리사   블랙핑크     와이지     여자  1997-03-27   167.0     A  1912800
14    로제   블랙핑크     와이지     여자  1997-02-11   168.0     B  1888132
15    윤아   소녀시대     에스엠     여자  1990-05-30   168.0     B  1885297
16    조이   레드벨벳     빅히트     여자  1996-09-03   168.0     A  1830514
17    슬기   레드벨벳     빅히트     여자  1994-02-10   161.0     A  1741767
18  강다니엘    워너원     NaN     남자  1996-12-10   182.0     A  1706444
19     진  방탄소년단     빅히트     남자  1992-12-04   179.0     O  1680587

In [85]:
# loc로 df에 company가 nan이 아닌 사람을 찾고 name, company, group, gender 항목만 뽑기
df.loc[df['company'].notnull(), ['name', 'company', 'group', 'gender']]

   name company  group gender
0    지민     빅히트  방탄소년단     남자
1    정국     빅히트  방탄소년단     남자
2    민지     어도어    뉴진스     여자
3    하니     어도어    뉴진스     여자
4     뷔     빅히트  방탄소년단     남자
5   다니엘     어도어    뉴진스     여자
6    혜인     어도어    뉴진스     여자
7    지수     와이지   블랙핑크     여자
8    해린     어도어    뉴진스     여자
9    태연     에스엠   소녀시대     여자
10   RM     빅히트  방탄소년단     남자
11   제니     와이지   블랙핑크     여자
12  옹성우    판타지오    워너원     남자
13   리사     와이지   블랙핑크     여자
14   로제     와이지   블랙핑크     여자
15   윤아     에스엠   소녀시대     여자
16   조이     빅히트   레드벨벳     여자
17   슬기     빅히트   레드벨벳     여자
19    진     빅히트  방탄소년단     남자